exec sp_executesql N'SELECT 
    1 AS [C1], 
    [Filter1].[GuidCompany] AS [GuidCompany], 
    [Filter1].[GuidUser1] AS [GuidUser], 
    [Filter1].[GuidUserCompany] AS [GuidUserCompany], 
    [Filter1].[CompanyAccepted] AS [CompanyAccepted], 
    [Filter1].[Useraccepted] AS [Useraccepted], 
    [Filter1].[CreatedBy1] AS [CreatedBy], 
    [Filter1].[CompanyUser] AS [CompanyUser], 
    [Filter1].[CreatedDate1] AS [CreatedDate], 
    [Filter1].[Disabled] AS [Disabled], 
    [Filter1].[IsDeleted1] AS [IsDeleted], 
    [Filter1].[GuidRole1] AS [GuidRole], 
    [Filter1].[LastSelectedDate] AS [LastSelectedDate], 
    [Filter1].[GuidModule1] AS [GuidModule], 
    [Filter1].[ENewsLetterSync1] AS [ENewsLetterSync], 
    [Filter1].[TotalItems] AS [TotalItems], 
    [Filter1].[UpdatedDateTotalItems] AS [UpdatedDateTotalItems], 
    [Filter1].[Name] AS [Name], 
    [Filter1].[PathModule] AS [PathModule], 
    [Filter1].[ModuleParentId] AS [ModuleParentId], 
    [Filter1].[TypeFullObject] AS [TypeFullObject], 
    [Filter1].[ModuleKey] AS [ModuleKey], 
    [Filter1].[ExtensibleInfo1] AS [ExtensibleInfo], 
    [Filter1].[ModuleNamespace] AS [ModuleNamespace], 
    [Filter1].[GuidModule2] AS [GuidModule1], 
    [Filter1].[IsAllowed] AS [IsAllowed], 
    [Filter1].[Name_EN] AS [Name_EN], 
    [Filter1].[Name_ES] AS [Name_ES], 
    [Filter1].[DescriptionShort] AS [DescriptionShort], 
    [Filter1].[DescriptionShort_ES] AS [DescriptionShort_ES], 
    [Filter1].[DescriptionShort_EN] AS [DescriptionShort_EN], 
    [Filter1].[DomainApp] AS [DomainApp], 
    [Filter1].[GuidAdminRole] AS [GuidAdminRole], 
    [Filter1].[Slogan] AS [Slogan], 
    [Filter1].[AllowAutoService] AS [AllowAutoService], 
    [Filter1].[ListIDNewsletter] AS [ListIDNewsletter], 
    [Filter1].[Langs] AS [Langs], 
    [Filter1].[WithPublicPage] AS [WithPublicPage], 
    [Filter1].[GuidAppTemplate] AS [GuidAppTemplate], 
    [Filter1].[RoleId] AS [RoleId], 
    [Filter1].[RoleName] AS [RoleName], 
    [Filter1].[LoweredRoleName] AS [LoweredRoleName], 
    [Filter1].[UpdatedDate1] AS [UpdatedDate], 
    [Filter1].[CreatedDate2] AS [CreatedDate1], 
    [Filter1].[GuidRole2] AS [GuidRole1], 
    [Filter1].[ParentGuidRole] AS [ParentGuidRole], 
    [Filter1].[CreatedBy2] AS [CreatedBy1], 
    [Filter1].[UpdatedBy1] AS [UpdatedBy], 
    [Filter1].[RoleName_ES] AS [RoleName_ES], 
    [Filter1].[RoleName_EN] AS [RoleName_EN], 
    [Filter1].[Description] AS [Description], 
    [Filter1].[Description_EN] AS [Description_EN], 
    [Filter1].[OwnerCompany] AS [OwnerCompany], 
    [Filter1].[IsDeleted2] AS [IsDeleted1], 
    [Filter1].[IsHeritable] AS [IsHeritable], 
    [Filter1].[UrlStartForced] AS [UrlStartForced], 
    [Filter1].[NameKey] AS [NameKey], 
    [Filter1].[UserId] AS [UserId], 
    [Filter1].[UserName] AS [UserName], 
    [Filter1].[LoweredUserName] AS [LoweredUserName], 
    [Filter1].[IsAnonymous] AS [IsAnonymous], 
    [Filter1].[LastActivityDate] AS [LastActivityDate], 
    [Filter1].[LastName] AS [LastName], 
    [Filter1].[FirstName] AS [FirstName], 
    [Filter1].[Password] AS [Password], 
    [Filter1].[Email] AS [Email], 
    [Filter1].[ExtensibleInfo2] AS [ExtensibleInfo1], 
    [Filter1].[UpdatedDate2] AS [UpdatedDate1], 
    [Filter1].[CreatedDate3] AS [CreatedDate2], 
    [Filter1].[DisplayName] AS [DisplayName], 
    [Filter1].[EmailVerified] AS [EmailVerified], 
    [Filter1].[GuidUser2] AS [GuidUser1], 
    [Filter1].[UpdatedBy2] AS [UpdatedBy1], 
    [Filter1].[CreatedBy3] AS [CreatedBy2], 
    [Filter1].[GuidFilePhoto] AS [GuidFilePhoto], 
    [Filter1].[Bio] AS [Bio], 
    [Filter1].[IsInvited] AS [IsInvited], 
    [Filter1].[EmailCodeVerirication] AS [EmailCodeVerirication], 
    [Filter1].[ENewsLetterSync2] AS [ENewsLetterSync1], 
    [Filter1].[Lang] AS [Lang], 
    [Filter1].[CountryCode] AS [CountryCode], 
    [Filter1].[IntegrationID] AS [IntegrationID], 
    [Filter1].[GuidAddedBy] AS [GuidAddedBy], 
    [Extent5].[Name] AS [Name1], 
    [Extent5].[GuidCompanyType] AS [GuidCompanyType], 
    [Extent5].[GuidCompany] AS [GuidCompany1], 
    [Extent5].[CompanyParentGuid] AS [CompanyParentGuid], 
    [Extent5].[UpdatedDate] AS [UpdatedDate2], 
    [Extent5].[CreatedDate] AS [CreatedDate3], 
    [Extent5].[UpdatedBy] AS [UpdatedBy2], 
    [Extent5].[CreatedBy] AS [CreatedBy3], 
    [Extent5].[IsDeleted] AS [IsDeleted2], 
    [Extent5].[GuidFileLogo] AS [GuidFileLogo], 
    [Extent5].[GuidCountry] AS [GuidCountry], 
    [Extent5].[GuidState] AS [GuidState], 
    [Extent5].[GuidCity] AS [GuidCity], 
    [Extent5].[GuidUserOwner] AS [GuidUserOwner], 
    [Extent5].[Description] AS [Description1], 
    [Extent5].[CanChildMoreChildren] AS [CanChildMoreChildren], 
    [Extent5].[CanChildsAdminRoles] AS [CanChildsAdminRoles], 
    [Extent5].[IntegrationID] AS [IntegrationID1], 
    [Extent5].[TimeZoneNameID] AS [TimeZoneNameID], 
    [Extent5].[ColorPrimary] AS [ColorPrimary], 
    [Extent5].[ColorBGApp] AS [ColorBGApp], 
    [Extent5].[ColorBGForm] AS [ColorBGForm]
    FROM   (SELECT [Extent1].[GuidCompany] AS [GuidCompany], [Extent1].[GuidUser] AS [GuidUser1], [Extent1].[GuidUserCompany] AS 
[GuidUserCompany], [Extent1].[CompanyAccepted] AS [CompanyAccepted], [Extent1].[Useraccepted] AS [Useraccepted], [Extent1].[CreatedBy] AS 
[CreatedBy1], [Extent1].[CompanyUser] AS [CompanyUser], [Extent1].[CreatedDate] AS [CreatedDate1], [Extent1].[Disabled] AS [Disabled], 
[Extent1].[IsDeleted] AS [IsDeleted1], [Extent1].[GuidRole] AS [GuidRole1], [Extent1].[LastSelectedDate] AS [LastSelectedDate], 
[Extent1].[GuidModule] AS [GuidModule1], [Extent1].[ENewsLetterSync] AS [ENewsLetterSync1], [Extent1].[TotalItems] AS [TotalItems], 
[Extent1].[UpdatedDateTotalItems] AS [UpdatedDateTotalItems], [Extent2].[Name] AS [Name], [Extent2].[PathModule] AS [PathModule], 
[Extent2].[ModuleParentId] AS [ModuleParentId], [Extent2].[TypeFullObject] AS [TypeFullObject], [Extent2].[ModuleKey] AS [ModuleKey], 
[Extent2].[ExtensibleInfo] AS [ExtensibleInfo1], [Extent2].[ModuleNamespace] AS [ModuleNamespace], [Extent2].[GuidModule] AS [GuidModule2], 
[Extent2].[IsAllowed] AS [IsAllowed], [Extent2].[Name_EN] AS [Name_EN], [Extent2].[Name_ES] AS [Name_ES], [Extent2].[DescriptionShort] AS 
[DescriptionShort], [Extent2].[DescriptionShort_ES] AS [DescriptionShort_ES], [Extent2].[DescriptionShort_EN] AS [DescriptionShort_EN], 
[Extent2].[DomainApp] AS [DomainApp], [Extent2].[GuidAdminRole] AS [GuidAdminRole], [Extent2].[Slogan] AS [Slogan], [Extent2].[AllowAutoService] 
AS [AllowAutoService], [Extent2].[ListIDNewsletter] AS [ListIDNewsletter], [Extent2].[Langs] AS [Langs], [Extent2].[WithPublicPage] AS [WithPublicPage], [Extent2].[GuidAppTemplate] AS [GuidAppTemplate], [Extent3].[RoleId] AS [RoleId], [Extent3].[RoleName] AS [RoleName], [Extent3].[LoweredRoleName] AS [LoweredRoleName], [Extent3].[UpdatedDate] AS [UpdatedDate1], [Extent3].[CreatedDate] AS [CreatedDate2], [Extent3].[GuidRole] AS [GuidRole2], [Extent3].[ParentGuidRole] AS [ParentGuidRole], [Extent3].[CreatedBy] AS [CreatedBy2], [Extent3].[UpdatedBy] AS [UpdatedBy1], [Extent3].[RoleName_ES] AS [RoleName_ES], [Extent3].[RoleName_EN] AS [RoleName_EN], [Extent3].[Description] AS [Description], [Extent3].[Description_EN] AS [Description_EN], [Extent3].[OwnerCompany] AS [OwnerCompany], [Extent3].[IsDeleted] AS [IsDeleted2], [Extent3].[IsHeritable] AS [IsHeritable], [Extent3].[UrlStartForced] AS [UrlStartForced], [Extent3].[NameKey] AS [NameKey], [Extent4].[UserId] AS [UserId], [Extent4].[UserName] AS [UserName], [Extent4].[LoweredUserName] AS [LoweredUserName], [Extent4].[IsAnonymous] AS [IsAnonymous], [Extent4].[LastActivityDate] AS [LastActivityDate], [Extent4].[LastName] AS [LastName], [Extent4].[FirstName] AS [FirstName], [Extent4].[Password] AS [Password], [Extent4].[Email] AS [Email], [Extent4].[ExtensibleInfo] AS [ExtensibleInfo2], [Extent4].[UpdatedDate] AS [UpdatedDate2], [Extent4].[CreatedDate] AS [CreatedDate3], [Extent4].[DisplayName] AS [DisplayName], [Extent4].[EmailVerified] AS [EmailVerified], [Extent4].[GuidUser] AS [GuidUser2], [Extent4].[UpdatedBy] AS [UpdatedBy2], [Extent4].[CreatedBy] AS [CreatedBy3], [Extent4].[GuidFilePhoto] AS [GuidFilePhoto], [Extent4].[Bio] AS [Bio], [Extent4].[IsInvited] AS [IsInvited], [Extent4].[EmailCodeVerirication] AS [EmailCodeVerirication], [Extent4].[ENewsLetterSync] AS [ENewsLetterSync2], [Extent4].[Lang] AS [Lang], [Extent4].[CountryCode] AS [CountryCode], [Extent4].[IntegrationID] AS [IntegrationID], [Extent4].[GuidAddedBy] AS [GuidAddedBy]
        FROM    [dbo].[secUserCompanies] AS [Extent1]
        LEFT OUTER JOIN [dbo].[secModule] AS [Extent2] ON [Extent1].[GuidModule] = [Extent2].[GuidModule]
        LEFT OUTER JOIN [dbo].[secRoles] AS [Extent3] ON [Extent1].[GuidRole] = [Extent3].[GuidRole]
        LEFT OUTER JOIN [dbo].[secUsers] AS [Extent4] ON [Extent1].[GuidUser] = [Extent4].[GuidUser]
        WHERE ([Extent1].[GuidRole] IS NOT NULL) AND ([Extent1].[GuidRole] IS NOT NULL) AND (( NOT ((1 = [Extent1].[IsDeleted]) AND ([Extent1].[IsDeleted] IS NOT NULL))) OR ([Extent1].[IsDeleted] IS NULL)) ) AS [Filter1]
    INNER JOIN [dbo].[secCompanies] AS [Extent5] ON [Filter1].[GuidCompany] = [Extent5].[GuidCompany]
    WHERE ([Filter1].[GuidUser1] = @p__linq__0) AND ([Filter1].[GuidUser1] = @p__linq__1)',N'@p__linq__0 uniqueidentifier,@p__linq__1 uniqueidentifier',@p__linq__0='F0F28D9B-CC32-4DE9-AE2D-23CB116FC780',@p__linq__1='F0F28D9B-CC32-4DE9-AE2D-23CB116FC780'